package defpackage;

import com.google.android.gms.common.api.Status;
import defpackage.vg;
import defpackage.vi;
import java.util.concurrent.TimeUnit;

/* renamed from: yj  reason: default package */
/* loaded from: classes2.dex */
public final class yj<R extends vi> extends vg<R> {
    final Status a;

    @Override // defpackage.vg
    public final void a(vg.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // defpackage.vg
    public final void a(vj<? super R> vjVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // defpackage.vg
    public final R a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
